// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package sqlc

import (
	"context"
)

type Querier interface {
	AddContact(ctx context.Context, arg AddContactParams) error
	AuthUser(ctx context.Context, arg AuthUserParams) (int32, error)
	CreateUser(ctx context.Context, arg CreateUserParams) error
	GetUser(ctx context.Context, uid int32) (GetUserRow, error)
}

var _ Querier = (*Queries)(nil)
