// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package sqlc

import (
	"context"
)

type Querier interface {
	AddContact(ctx context.Context, arg AddContactParams) error
	ApplyAllRoles(ctx context.Context, arg ApplyAllRolesParams) error
	ApplyUserRole(ctx context.Context, uid int32) error
	AuthUser(ctx context.Context, arg AuthUserParams) (int32, error)
	CreateAdoption(ctx context.Context, arg CreateAdoptionParams) error
	CreateCategory(ctx context.Context, arg CreateCategoryParams) error
	CreatePet(ctx context.Context, arg CreatePetParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) error
	DeletePet(ctx context.Context, petID int32) error
	GetCategoryID(ctx context.Context, arg GetCategoryIDParams) (int32, error)
	GetContacts(ctx context.Context, uid int32) ([]GetContactsRow, error)
	GetRoles(ctx context.Context, uid int32) ([]string, error)
	GetUser(ctx context.Context, uid int32) (GetUserRow, error)
	ListAvailablePet(ctx context.Context, uid int32) ([]ListAvailablePetRow, error)
	ListPet(ctx context.Context, uid int32) ([]ListPetRow, error)
	ListReviewerAdoption(ctx context.Context, uid int32) ([]ListReviewerAdoptionRow, error)
	ListUserAdoption(ctx context.Context, uid int32) ([]ListUserAdoptionRow, error)
	UpdateAdoptionReview(ctx context.Context, arg UpdateAdoptionReviewParams) error
	UpdatePet(ctx context.Context, arg UpdatePetParams) error
}

var _ Querier = (*Queries)(nil)
