// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: role.sql

package sqlc

import (
	"context"
)

const applyAllRoles = `-- name: ApplyAllRoles :exec
insert into user_role (
    ` + "`" + `uid` + "`" + `,
    role_id
) values
    (?, 1),
    (?, 2),
    (?, 3)
`

type ApplyAllRolesParams struct {
	Uid int32 `json:"uid"`
}

func (q *Queries) ApplyAllRoles(ctx context.Context, arg ApplyAllRolesParams) error {
	_, err := q.db.ExecContext(ctx, applyAllRoles, arg.Uid, arg.Uid, arg.Uid)
	return err
}

const applyUserRole = `-- name: ApplyUserRole :exec
insert into user_role (
    ` + "`" + `uid` + "`" + `,
    role_id
) values (
    ?, 3
)
`

func (q *Queries) ApplyUserRole(ctx context.Context, uid int32) error {
	_, err := q.db.ExecContext(ctx, applyUserRole, uid)
	return err
}
